#!/usr/bin/env bash

set -ue

# booting the strap from livecd (or gentoo-prefix if later)
ID="$1"
PREFIX="$2"

if ! findmnt "${PREFIX}" > /dev/null; then
  echo "please mount ${PREFIX} first"
  exit 1
fi

if [[ ! -f "${PREFIX}/bin/bash" ]]; then
  echo "\$ untar stage3"
  case "$(uname -m)" in
    x86_64)
      arch="amd64" ;;
  esac
  url="https://mirrors.tuna.tsinghua.edu.cn/gentoo/releases/${arch}/autobuilds"
  version="$(curl -s "${url}/latest-stage3-${arch}-systemd.txt" \
    | grep stage3 | awk '{print $1}')"
  curl -so stage3.tar.xz "${url}/${version}"
  tar xpf stage3.tar.xz --xattrs-include='*.*' --numeric-owner -C "${PREFIX}"
  rm stage3.tar.xz
fi

if [[ ! -f "${PREFIX}/var/db/repos/aptenodytes/noot" ]]; then
  echo "\$ repos aptenodytes"
  url="https://raw.githubusercontent.com/plxty/aptenodytes/refs/heads/main/sys-apps/portage-p/files"
  # making use of the git from livecd
  mkdir -p {,"${PREFIX}"}/etc/portage/repos.conf
  curl -so /etc/portage/repos.conf/gentoo.conf | \
    EPREFIX="${PREFIX}" envsubst '${EPREFIX}' > "${url}/gentoo.conf"
  emerge --sync
  cp {,"${PREFIX}"}/etc/portage/repos.conf/gentoo.conf
  cp -Ta {,"${PREFIX}"}/var/db/repos
fi

if ! readlink "${PREFIX}/etc/portage/make.profile" | grep -q aptenodytes; then
  echo "\$ profile ${ID}"
  arch-chroot "${PREFIX}" eselect profile set "aptenodytes:iglu/${ID}"
fi

if [[ ! -f "${PREFIX}/etc/hostname" ]]; then
  echo "\$ emerge boot"
  cp -f {,"${PREFIX}"}/etc/resolv.conf
  arch-chroot "${PREFIX}" emerge -1 sci-misc/aptenodytes
fi

if [[ ! -d "${PREFIX}/usr/lib/modules" ]]; then
  echo "\$ make kernel"
  arch-chroot "${PREFIX}" emerge -uNDv @world
fi

for user in $(grep superego "${PREFIX}/etc/portage/make.profile/parent" | awk -F/ '{print $NF}'); do
  echo "\$ passwd ${user}"
  arch-chroot "${PREFIX}" passwd "${user}"
done
