[DEFAULT]
main-repo = gentoo

[guru]
priority = 0
location = ${EPREFIX}/var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo/guru.git
auto-sync = yes

[gentoo-zh]
priority = 1
location = ${EPREFIX}/var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://mirror.nju.edu.cn/git/gentoo-zh.git
auto-sync = yes

[aptenodytes]
priority = 2
location = ${EPREFIX}/var/db/repos/aptenodytes
sync-type = git
sync-uri = https://github.com/plxty/aptenodytes.git
auto-sync = yes
