[DEFAULT]
main-repo = gentoo

[gentoo]
priority = 0
location = /var/db/repos/gentoo
sync-type = git
sync-uri = https://mirrors.tuna.tsinghua.edu.cn/git/gentoo-portage.git
auto-sync = yes
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
sync-openpgp-keyserver = https://keys.gentoo.org
sync-openpgp-key-refresh-retry-count = 40
sync-openpgp-key-refresh-retry-overal-timeout = 1200
sync-openpgp-key-refresh-retry-delay-exp-base = 2
sync-openpgp-key-refresh-retry-delay-max = 60
sync-openpgp-key-refresh-retry-delay-mult = 4
sync-git-verify-commit-signature = true

[guru]
priority = 1
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo/guru.git
auto-sync = yes

[gentoo-zh]
priority = 2
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://mirror.nju.edu.cn/git/gentoo-zh.git
auto-sync = yes

[aptenodytes]
priority = 3
location = /var/db/repos/aptenodytes
sync-type = git
sync-uri = https://github.com/plxty/aptenodytes.git
auto-sync = yes
