theme = "papercolor-dark"

[editor]
auto-format = false
color-modes = true
line-number = "relative"
rulers = [80, 120]
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-ignore = true
hidden = true

[keys.insert]
"A-;" = "command_mode"
A-b = "move_prev_word_start"
A-f = "move_next_word_end"
A-x = "command_palette"
C-a = "goto_line_start"
C-b = "move_char_left"
C-e = "goto_line_end_newline"
C-f = "move_char_right"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-n = "move_line_down"
C-p = "move_line_up"

[keys.normal]
"#" = "select_references_to_symbol_under_cursor"
";" = "goto_word_definition"
A-J = ["extend_to_line_bounds", "yank", "paste_after"]
A-K = ["extend_to_line_bounds", "yank", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
G = "goto_last_line"
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.normal."'"]
"'" = ":config-reload"
a = ":toggle soft-wrap.enable"
c = ":toggle search.case-sensitive"
f = ":toggle auto-format"
h = [":toggle file-picker.hidden", ":toggle file-picker.git-ignore"]
m = [":format", ":write --format"]
p = ":toggle auto-pairs"
r = ":toggle search.regex"
s = ":toggle search.smart-case"
t = ":toggle smart-tab.enable"
w = ":toggle search.whole-word"

[keys.normal.","]
"," = "collapse_selection"
"." = "keep_primary_selection"
"/" = "remove_primary_selection"
";" = "flip_selections"

[keys.normal.g]
";" = "goto_word_reference"
R = ["goto_prev_function_name", "goto_reference"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"

